### ISSUE TITLE
please don't override settings

### ISSUE THREAD

**Issue by eyelash** [TingPing/language-meson#2]
This package overrides some of my default settings for Meson files like the tab length and tab type. Is there a good reason for that as Meson does not mandate a certain tab length or tab type? I'm trying to set the values back to my editor defaults (tab length 4) in the package settings but Atom won't let me as it claims that 4 is already the default.

![meson](https://user-images.githubusercontent.com/2668288/31860589-9017aabe-b71c-11e7-82f0-784b2fb027e7.png)

**Comment by TingPing** [comment]
> I'm trying to set the values back to my editor defaults (tab length 4) in the package settings but Atom won't let me as it claims that 4 is already the default.

That sounds like a bug to take up with Atom.

2 is used because that is Meson convention.

**Comment by eyelash** [comment]
> 2 is used because that is Meson convention.

I couldn't find information about this in the Meson documentation.

**Comment by TingPing** [comment]
It is possible it isn't documented, but the hundreds of tests in the Meson project follow the convention: https://github.com/mesonbuild/meson/tree/master/test%20cases

**Comment by eyelash** [comment]
I still disagree. Even if it is a convention in Meson as long as Meson works with any indentation I don't think a package should override my general settings. The elementary guys use 4 spaces for all their Meson files for example.

**Comment by TingPing** [comment]
It is just a default, you change it in preferences.
