### ISSUE TITLE
Update the logo for your Meson plugin.

### ISSUE THREAD

**Issue by squidfarts** [TingPing/language-meson#5]
Hello.
I have bean a Meson build user starting with version 0.49.999 and currently using version 0.52.0 and like to keep things compatible from 0.50.0 and up.

I think it would be nice if the logo was changed to reflect the new logo design.  🙂

**Comment by TingPing** [comment]
This repo doesn't contain any logos?

**Comment by squidfarts** [comment]
So.  Not this.

![2019-09-08_20-17-59](https://user-images.githubusercontent.com/42789598/64501335-c931c700-d275-11e9-9b5d-69fedbe7cf23.png)

**Comment by TingPing** [comment]
That is somebody elses extensions that just uses the grammar from here. So you have to talk to them about the logo they choose.
